extends Control

const SESSION_SCRIPT := "res://addons/narrrail/runtime/narrrail_session.gd"
const LOADER_SCRIPT := "res://addons/narrrail/importer/nrstory_loader.gd"
const STORY_DIR := "res://sample/stories"
const DEFAULT_STORY_PATH := "res://sample/stories/demo.nrstory"

@onready var story_option: OptionButton = $Panel/Margin/VBox/StoryBar/StoryOption
@onready var path_edit: LineEdit = $Panel/Margin/VBox/StoryBar/PathEdit
@onready var load_button: Button = $Panel/Margin/VBox/StoryBar/LoadButton
@onready var refresh_button: Button = $Panel/Margin/VBox/StoryBar/RefreshButton
@onready var speaker_label: Label = $Panel/Margin/VBox/SpeakerLabel
@onready var text_label: Label = $Panel/Margin/VBox/TextLabel
@onready var choices_box: VBoxContainer = $Panel/Margin/VBox/ChoicesBox
@onready var next_button: Button = $Panel/Margin/VBox/BottomBar/NextButton
@onready var status_label: Label = $Panel/Margin/VBox/BottomBar/StatusLabel

var _session: RefCounted
var _story_paths: Array[String] = []

func _ready() -> void:
	next_button.pressed.connect(_on_next_pressed)
	load_button.pressed.connect(_on_load_pressed)
	refresh_button.pressed.connect(_on_refresh_pressed)
	story_option.item_selected.connect(_on_story_selected)
	path_edit.text_submitted.connect(func(_text: String) -> void:
		_on_load_pressed()
	)

	_refresh_story_list()
	_load_story_path(_selected_or_default_path())

func _create_session() -> bool:
	var session_script: Script = load(SESSION_SCRIPT)
	if session_script == null:
		_push_status("Failed to load session script")
		return false

	_session = session_script.new()
	_session.line_changed.connect(_on_line_changed)
	_session.choices_changed.connect(_on_choices_changed)
	_session.ended.connect(_on_ended)
	_session.error_raised.connect(_on_error)
	return true

func _load_story_path(path: String) -> void:
	_clear_story_view()
	if path.strip_edges().is_empty():
		_push_status("Empty story path")
		return

	path_edit.text = path
	if not _create_session():
		return

	var story := _load_story_from_file_or_fallback(path)
	_session.start(story)
	if _session.get_state().get("state", "") != "ended":
		_push_status("Running: %s" % path)

func _load_story_from_file_or_fallback(path: String) -> Dictionary:
	# 1) Prefer Godot import pipeline result (Resource generated by EditorImportPlugin)
	var imported := load(path)
	if imported != null:
		var maybe_story = imported.get("story_data")
		if typeof(maybe_story) == TYPE_DICTIONARY and not (maybe_story as Dictionary).is_empty():
			_push_status("Loaded imported resource: %s" % path)
			return maybe_story

	# 2) Fallback to direct loader parse
	var loader_script: Script = load(LOADER_SCRIPT)
	if loader_script == null:
		_push_status("Loader missing, fallback to built-in story")
		return _build_demo_story()

	var result: Dictionary = loader_script.call("load_story", path)
	if not result.get("ok", false):
		_push_status("Load failed, fallback: %s" % _format_diagnostics(result))
		return _build_demo_story()

	var diagnostics: Array = result.get("diagnostics", [])
	if not diagnostics.is_empty():
		_push_status("Loaded with diagnostics: %s" % _format_diagnostics(result))
	else:
		_push_status("Loaded direct parse: %s" % path)

	return result.get("story", {})

func _refresh_story_list() -> void:
	_story_paths.clear()
	story_option.clear()

	var dir := DirAccess.open(STORY_DIR)
	if dir != null:
		dir.list_dir_begin()
		var file_name := dir.get_next()
		while not file_name.is_empty():
			if not dir.current_is_dir() and file_name.ends_with(".nrstory"):
				_story_paths.append("%s/%s" % [STORY_DIR, file_name])
			file_name = dir.get_next()
		dir.list_dir_end()

	_story_paths.sort()
	if _story_paths.is_empty():
		_story_paths.append(DEFAULT_STORY_PATH)

	for path in _story_paths:
		story_option.add_item(path.get_file())
		story_option.set_item_metadata(story_option.item_count - 1, path)

	var selected_index := _story_paths.find(path_edit.text)
	if selected_index < 0:
		selected_index = max(_story_paths.find(DEFAULT_STORY_PATH), 0)
	story_option.select(selected_index)
	path_edit.text = _story_paths[selected_index]

func _selected_or_default_path() -> String:
	if story_option.selected >= 0:
		return String(story_option.get_item_metadata(story_option.selected))
	if not path_edit.text.strip_edges().is_empty():
		return path_edit.text.strip_edges()
	return DEFAULT_STORY_PATH

func _build_demo_story() -> Dictionary:
	return {
		"meta": {
			"schemaVersion": 1,
			"storyId": "demo_ui",
			"entryNodeId": "N_Start"
		},
		"variables": [],
		"nodes": [
			{
				"nodeId": "N_Start",
				"nodeType": "Dialogue",
				"dialogue": {"speakerId": "Hero", "textKey": "你好，今天一起去散步吗？"}
			},
			{
				"nodeId": "N_Choice",
				"nodeType": "Choice",
				"choices": [
					{"textKey": "好啊，一起去！", "targetNodeId": "N_Yes"},
					{"textKey": "今天先不了。", "targetNodeId": "N_No"}
				]
			},
			{
				"nodeId": "N_Yes",
				"nodeType": "Dialogue",
				"dialogue": {"speakerId": "Hero", "textKey": "太好了，那我们出发吧！"}
			},
			{
				"nodeId": "N_No",
				"nodeType": "Dialogue",
				"dialogue": {"speakerId": "Hero", "textKey": "没关系，下次再约。"}
			},
			{
				"nodeId": "N_End",
				"nodeType": "End"
			}
		],
		"edges": [
			{"sourceNodeId": "N_Start", "targetNodeId": "N_Choice", "priority": 0, "condition": {"logic": "All", "terms": []}},
			{"sourceNodeId": "N_Yes", "targetNodeId": "N_End", "priority": 0, "condition": {"logic": "All", "terms": []}},
			{"sourceNodeId": "N_No", "targetNodeId": "N_End", "priority": 0, "condition": {"logic": "All", "terms": []}}
		]
	}

func _on_line_changed(payload: Dictionary) -> void:
	speaker_label.text = "Speaker: %s" % String(payload.get("speakerId", ""))
	text_label.text = String(payload.get("textKey", ""))
	_clear_choices()
	next_button.disabled = false

func _on_choices_changed(choices: Array) -> void:
	_clear_choices()
	next_button.disabled = true
	for i in range(choices.size()):
		var c: Dictionary = choices[i]
		var btn := Button.new()
		btn.text = String(c.get("textKey", "Choice %d" % i))
		btn.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		btn.pressed.connect(func() -> void:
			_session.choose(i)
		)
		choices_box.add_child(btn)

func _on_ended() -> void:
	_clear_choices()
	next_button.disabled = true
	_push_status("Ended")

func _on_error(message: String) -> void:
	_push_status("Error: %s" % message)
	next_button.disabled = true

func _on_next_pressed() -> void:
	if _session != null:
		_session.next()

func _on_load_pressed() -> void:
	_load_story_path(path_edit.text.strip_edges())

func _on_refresh_pressed() -> void:
	var current_path := path_edit.text.strip_edges()
	_refresh_story_list()
	if not current_path.is_empty():
		path_edit.text = current_path
	_load_story_path(path_edit.text.strip_edges())

func _on_story_selected(index: int) -> void:
	var path := String(story_option.get_item_metadata(index))
	path_edit.text = path
	_load_story_path(path)

func _clear_choices() -> void:
	for child in choices_box.get_children():
		child.queue_free()

func _clear_story_view() -> void:
	_clear_choices()
	speaker_label.text = "Speaker: "
	text_label.text = ""
	next_button.disabled = true

func _format_diagnostics(result: Dictionary) -> String:
	var diagnostics: Array = result.get("diagnostics", [])
	if diagnostics.is_empty():
		return String(result.get("error", "unknown"))

	var parts: Array[String] = []
	for d in diagnostics:
		var sev := String(d.get("severity", ""))
		var code := String(d.get("code", ""))
		var path := String(d.get("path", ""))
		var msg := String(d.get("message", ""))
		parts.append("[%s][%s] %s: %s" % [sev, code, path, msg])
	return " | ".join(parts)

func _push_status(text: String) -> void:
	status_label.text = text
